"use strict";
const state={calculated:false,type:"normal",params:{mean:0,sd:1,df:10},p:.95,q:null};
const $=id=>document.getElementById(id),fmt=x=>Math.abs(x)>=1000?x.toPrecision(6):Number(x.toPrecision(7)).toString();
function erf(x){const sign=x<0?-1:1,a=Math.abs(x),t=1/(1+.3275911*a);return sign*(1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-a*a)))}
function normalPdf(x,m=0,s=1){const z=(x-m)/s;return Math.exp(-z*z/2)/(s*Math.sqrt(2*Math.PI))}
function normalCdf(x){return .5*(1+erf(x/Math.SQRT2))}
function normalInv(p){const a=[-39.6968302866538,220.946098424521,-275.928510446969,138.357751867269,-30.6647980661472,2.50662827745924],b=[-54.4760987982241,161.585836858041,-155.698979859887,66.8013118877197,-13.2806815528857],c=[-.00778489400243029,-.322396458041136,-2.40075827716184,-2.54973253934373,4.37466414146497,2.93816398269878],d=[.00778469570904146,.32246712907004,2.445134137143,3.75440866190742],pl=.02425,ph=1-pl;let q,r;if(p<pl){q=Math.sqrt(-2*Math.log(p));return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}if(p>ph){q=Math.sqrt(-2*Math.log(1-p));return-(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}q=p-.5;r=q*q;return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)}
function logGamma(z){const c=[.9999999999998099,676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.5073432786869,-.13857109526572,9.98436957801957e-6,1.50563273514931e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z--;let x=c[0];for(let i=1;i<c.length;i++)x+=c[i]/(z+i);const t=z+7.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function betaCF(a,b,x){let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<3e-14)d=3e-14;d=1/d;let h=d;for(let m=1;m<=180;m++){let m2=2*m,aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<3e-14)d=3e-14;c=1+aa/c;if(Math.abs(c)<3e-14)c=3e-14;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<3e-14)d=3e-14;c=1+aa/c;if(Math.abs(c)<3e-14)c=3e-14;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break}return h}
function regBeta(x,a,b){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaCF(a,b,x)/a:1-bt*betaCF(b,a,1-x)/b}
function tPdf(x,v){return Math.exp(logGamma((v+1)/2)-logGamma(v/2))/(Math.sqrt(v*Math.PI))*Math.pow(1+x*x/v,-(v+1)/2)}
function tCdf(x,v){const z=v/(v+x*x),tail=.5*regBeta(z,v/2,.5);return x>=0?1-tail:tail}
function tInv(p,v){if(p===.5)return 0;let lo=-1,hi=1;while(tCdf(lo,v)>p)lo*=2;while(tCdf(hi,v)<p)hi*=2;for(let i=0;i<90;i++){const mid=(lo+hi)/2;tCdf(mid,v)<p?lo=mid:hi=mid}return(lo+hi)/2}
function valid(){const p=+$('probability').value;if(!(p>0&&p<1))return'Cumulative probability must be greater than 0 and less than 1.';if(state.type==='normal'){const sd=+$('sd').value;if(!(sd>0))return'Standard deviation must be greater than 0.'}else{const df=+$('df').value;if(!(Number.isInteger(df)&&df>=1&&df<=10000))return'Degrees of freedom must be an integer from 1 to 10,000.'}return''}
function sync(){state.p=+$('probability').value;if(state.type==='normal'){state.params.mean=+$('mean').value;state.params.sd=+$('sd').value}else state.params.df=+$('df').value}
function calculate(){sync();const message=valid();$('error').textContent=message;if(message){state.q=null;renderPlot();return}state.q=state.type==='normal'?state.params.mean+state.params.sd*normalInv(state.p):tInv(state.p,state.params.df);state.calculated=true;renderResult();renderPlot()}
function renderParams(){const p=$('parameters');p.innerHTML=state.type==='normal'?`<div class="field"><label for="mean">Mean (μ)</label><input id="mean" type="number" step="any" value="${state.params.mean}"></div><div class="field"><label for="sd">Standard deviation (σ)</label><input id="sd" type="number" min="0" step="any" value="${state.params.sd}"></div>`:`<div class="field" style="grid-column:1/-1"><label for="df">Degrees of freedom (ν)</label><input id="df" type="number" min="1" max="10000" step="1" value="${state.params.df}"></div>`;p.querySelectorAll('input').forEach(el=>el.addEventListener('input',changed))}
function renderResult(){const el=$('result');if(!state.calculated||!Number.isFinite(state.q)){el.className='result placeholder';el.innerHTML='<span class="result-label">Calculated quantile</span><strong class="result-value">Enter a probability and calculate</strong>';return}el.className='result';const detail=state.type==='normal'?`Normal(μ = ${fmt(state.params.mean)}, σ = ${fmt(state.params.sd)})`:`Student’s t with ${state.params.df} degrees of freedom`;el.innerHTML=`<span class="result-label">Calculated quantile</span><strong class="result-value">${fmt(state.q)}</strong><span class="result-detail">${detail}</span><span class="result-detail">P(X ≤ ${fmt(state.q)}) = ${fmt(state.p)}</span>`}
function changed(){sync();$('error').textContent=valid();if(state.calculated&&!valid())calculate();else{if(state.calculated)calculate();else renderPlot()}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderPlot(){const svg=$('plot'),W=760,H=440,L=64,R=24,T=25,B=62,w=W-L-R,h=H-T-B,ok=!valid(),q=state.calculated&&ok?state.q:null,p=state.params;let lo,hi,pdf,title,axis;if(state.type==='normal'){const reach=q==null?4:Math.max(4,Math.abs((q-p.mean)/p.sd)+.65);lo=p.mean-reach*p.sd;hi=p.mean+reach*p.sd;pdf=x=>normalPdf(x,p.mean,p.sd);title='Normal distribution';axis='Value of X'}else{const df=p.df||10,base=df<=2?10:df<=5?7:5.2,reach=q==null?base:Math.max(base,Math.abs(q)*1.18+.5);lo=-reach;hi=reach;pdf=x=>tPdf(x,df);title=`Student’s t distribution (ν = ${df})`;axis='t value'}$('plotTitle').textContent=title;const n=420,xs=[],ys=[];for(let i=0;i<=n;i++){const x=lo+(hi-lo)*i/n;xs.push(x);ys.push(ok?pdf(x):0)}const ymax=Math.max(...ys)*1.13||1,X=x=>L+(x-lo)/(hi-lo)*w,Y=y=>T+h-y/ymax*h,path=xs.map((x,i)=>(i?'L':'M')+X(x).toFixed(2)+' '+Y(ys[i]).toFixed(2)).join(' ');let html='';for(let i=0;i<=4;i++){const yy=T+h*i/4;html+=`<line class="grid" x1="${L}" x2="${W-R}" y1="${yy}" y2="${yy}"/>`}if(q!=null){const shadeXs=xs.filter(x=>x<=q);if(q>lo&&q<hi)shadeXs.push(q);const area=[`M ${X(lo)} ${T+h}`,...shadeXs.map(x=>`L ${X(x)} ${Y(pdf(x))}`),`L ${X(Math.min(q,hi))} ${T+h} Z`].join(' ');html+=`<path class="area" d="${area}"/>`}html+=`<path class="curve" d="${path}"/><line class="axis" x1="${L}" x2="${W-R}" y1="${T+h}" y2="${T+h}"/><line class="axis" x1="${L}" x2="${L}" y1="${T}" y2="${T+h}"/>`;for(let i=0;i<=5;i++){const x=lo+(hi-lo)*i/5,px=X(x);html+=`<line class="axis" x1="${px}" x2="${px}" y1="${T+h}" y2="${T+h+6}"/><text class="tick" x="${px}" y="${T+h+22}" text-anchor="middle">${esc(fmt(x))}</text>`}html+=`<text class="axis-title" x="${L+w/2}" y="${H-8}" text-anchor="middle">${axis}</text><text class="axis-title" transform="translate(18 ${T+h/2}) rotate(-90)" text-anchor="middle">Probability density</text>`;if(q!=null){const qx=X(q);html+=`<line class="quantile-line" x1="${qx}" x2="${qx}" y1="${T+4}" y2="${T+h}"/><text class="plot-label" x="${Math.min(W-R-5,Math.max(L+5,qx))}" y="${T+h+42}" text-anchor="middle">q = ${esc(fmt(q))}</text><text class="prob-label" x="${Math.max(L+82,Math.min(qx-12,W-R-92))}" y="${T+45}" text-anchor="middle">P(X ≤ q) = ${esc(fmt(state.p))}</text>`}else html+=`<text class="empty-note" x="${L+w/2}" y="${T+42}" text-anchor="middle">Density curve shown with current parameters</text>`;svg.innerHTML=html;const description=q==null?`${title} density curve using the current parameters. No probability region is shaded before calculation.`:`${title} density curve. The area to the left of quantile ${fmt(q)} is shaded and equals cumulative probability ${fmt(state.p)}. The vertical axis is probability density, not cumulative probability.`;$('plotDescription').textContent=description;$('plotSubtitle').textContent=q==null?'Density is curve height; calculate to shade a cumulative area.':`Shaded area = ${fmt(state.p)}. Curve height is density; shaded area is probability.`}
function initialize(){
 const distribution=$('distribution'),probability=$('probability'),button=$('calculate');
 if(!distribution||!probability||!button)return;
 distribution.addEventListener('change',e=>{state.type=e.target.value;state.calculated=false;state.q=null;renderParams();renderResult();renderPlot()});
 probability.addEventListener('input',changed);button.addEventListener('click',calculate);
 renderParams();renderResult();renderPlot();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize);else initialize();
